// @ts-nocheck
document.addEventListener("DOMContentLoaded",function(){
"use strict";
if(typeof firebase==="undefined")return;
const FIREBASE_CONFIG={apiKey:"AIzaSyBFLPbBQPZy4ILeBRZ_kELi7KizlR1hgJo",authDomain:"urbanx-92e74.firebaseapp.com",projectId:"urbanx-92e74",storageBucket:"urbanx-92e74.firebasestorage.app",messagingSenderId:"830520272633",appId:"1:830520272633:web:ce7f2bf7abc8f86fec6428"};
const APP_NAME="sixteen-admin";let app=firebase.apps.find(a=>a.name===APP_NAME);if(!app)app=firebase.initializeApp(FIREBASE_CONFIG,APP_NAME);const db=firebase.firestore(app);const FV=firebase.firestore.FieldValue;const C=db.collection("facturacion");const CFG=C.doc("config_interna");const $=id=>document.getElementById(id);const e={badge:$("facturacionPendientesBadge"),pedido:$("facturacionPedidoSelect"),fecha:$("facturacionFechaEmision"),preview:$("facturacionPedidoPreview"),generar:$("generarFacturaXmlBtn"),msg:$("facturacionGenerarMensaje"),buscar:$("facturacionBuscar"),tipo:$("facturacionFiltroTipo"),estado:$("facturacionFiltroEstado"),exportar:$("exportarFacturacionCsvBtn"),body:$("facturacionBody"),kTotal:$("facturacionKpiTotal"),kFac:$("facturacionKpiFacturas"),kNc:$("facturacionKpiNotasCredito"),kMonto:$("facturacionKpiTotalFacturado"),openNc:$("abrirNotaCreditoBtn"),openNd:$("abrirNotaDebitoBtn"),modal:$("facturacionNotaModal"),modalPanel:$("facturacionNotaModal")?.querySelector(".admin-modal-panel"),modalTitle:$("facturacionNotaTitulo"),closeModal:$("cerrarFacturacionNotaBtn"),cancelModal:$("cancelarFacturacionNotaBtn"),noteForm:$("facturacionNotaForm"),noteInvoice:$("facturacionNotaFactura"),noteValue:$("facturacionNotaValor"),noteReason:$("facturacionNotaMotivo"),noteInfo:$("facturacionNotaInfo"),noteMsg:$("facturacionNotaMensaje"),noteSave:$("guardarFacturacionNotaBtn")};
if(!e.body)return;
let orders=[],docs=[],noteType="NOTA_CREDITO",lastFocus=null;
const txt=v=>String(v==null?"":v).trim();const num=v=>Number.isFinite(Number(v))?Number(v):0;const money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(num(v));const clean=s=>txt(s).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};const safeId=s=>txt(s).replace(/[^A-Za-z0-9_-]/g,"_").slice(0,120);
function setMsg(message,error=false){if(!e.msg)return;e.msg.textContent=message||"";e.msg.classList.toggle("error",!!error);}
function buyer(order){const c=order?.cliente||{};return {razonSocial:[c.nombres,c.apellidos].filter(Boolean).join(" ").trim()||c.email||"Cliente SIXTEEN",nombres:txt(c.nombres),apellidos:txt(c.apellidos),identificacion:txt(c.identificacion),email:txt(c.email).toLowerCase(),telefono:txt(c.telefono),direccion:txt(order?.entrega?.direccion),ciudad:txt(order?.entrega?.ciudad),provincia:txt(order?.entrega?.provincia)};}
function detail(order){return (Array.isArray(order?.productos)?order.productos:[]).map(x=>({codigo:txt(x.codigo),descripcion:txt(x.nombre),categoria:txt(x.categoria),cantidad:Math.max(0,num(x.cantidad)),precioUnitario:Math.max(0,num(x.precioUnitario)),color:txt(x.color),talla:txt(x.talla),varianteId:txt(x.varianteId)}));}
function totals(order){const r=order?.resumen||{};return {subtotal:Math.max(0,num(r.subtotal)),descuento:Math.max(0,num(r.descuento)),envio:Math.max(0,num(r.envio)),importeTotal:Math.max(0,num(r.total)),cupon:r.cupon||null};}
function typeName(t){return ({FACTURA:"Factura",NOTA_CREDITO:"Nota de crédito",NOTA_DEBITO:"Nota de débito"})[t]||"Documento";}
function seq(prefix,n){return `${prefix}-${String(n).padStart(9,"0")}`;}
function isInternal(x){return x&&x.sistema==="SIXTEEN_INTERNO"&&x.tipoRegistro==="DOCUMENTO";}
function invoiceForOrder(id){return docs.find(x=>x.tipoDocumento==="FACTURA"&&x.pedidoId===id&&x.estado!=="ANULADA")||null;}
function clear(node){while(node?.firstChild)node.removeChild(node.firstChild);}
function span(text,cls){const s=document.createElement("span");if(cls)s.className=cls;s.textContent=text;return s;}
function renderOrders(){if(!e.pedido)return;const selected=e.pedido.value;clear(e.pedido);const o=document.createElement("option");o.value="";o.textContent="Selecciona un pedido";e.pedido.append(o);orders.filter(x=>txt(x.estado)!=="Cancelado"&&!invoiceForOrder(x.id)).sort((a,b)=>(b.creadoEn?.seconds||0)-(a.creadoEn?.seconds||0)).forEach(x=>{const op=document.createElement("option");op.value=x.id;op.textContent=`${txt(x.numero||x.id)} · ${txt(x.cliente?.nombres)} ${txt(x.cliente?.apellidos)} · ${money(x.resumen?.total)}`;e.pedido.append(op)});if([...e.pedido.options].some(x=>x.value===selected))e.pedido.value=selected;renderPreview();}
function renderPreview(){if(!e.preview)return;clear(e.preview);const o=orders.find(x=>x.id===e.pedido?.value);if(!o){e.preview.textContent="Selecciona un pedido para revisar los datos que se usarán en la factura.";return;}const b=buyer(o);const parts=[`Pedido: ${txt(o.numero||o.id)}`,`Cliente: ${b.razonSocial}`,`Identificación: ${b.identificacion||"—"}`,`Pago: ${txt(o.pago?.nombre||o.pago?.metodo)||"—"}`,`Productos: ${(o.productos||[]).length}`,`Total: ${money(o.resumen?.total)}`];parts.forEach(x=>{const p=document.createElement("p");p.textContent=x;e.preview.append(p)});}
async function createInvoice(){const order=orders.find(x=>x.id===e.pedido?.value);if(!order){setMsg("Selecciona un pedido.",true);return;}if(invoiceForOrder(order.id)){setMsg("Este pedido ya tiene una factura SIXTEEN activa.",true);return;}e.generar.disabled=true;setMsg("Generando factura...");try{let created=null,createdId="";await db.runTransaction(async tx=>{const lockRef=C.doc("lock_pedido_"+safeId(order.id));const lockSnap=await tx.get(lockRef);if(lockSnap.exists&&txt(lockSnap.data()?.activeFacturaId)){const activeRef=C.doc(txt(lockSnap.data().activeFacturaId));const activeSnap=await tx.get(activeRef);if(activeSnap.exists&&activeSnap.data()?.estado!=="ANULADA")throw new Error("Este pedido ya tiene una factura SIXTEEN activa.");}const cfgSnap=await tx.get(CFG);const cfg=cfgSnap.exists?cfgSnap.data():{};const n=Math.max(1,Math.floor(num(cfg.proximoFactura)||1));const number=seq("SIX-FAC",n);const ref=C.doc(`factura_${safeId(order.id)}_${String(n).padStart(9,"0")}`);const existing=await tx.get(ref);if(existing.exists)throw new Error("No fue posible reservar el número de factura. Intenta nuevamente.");createdId=ref.id;created={tipoRegistro:"DOCUMENTO",sistema:"SIXTEEN_INTERNO",version:1,tipoDocumento:"FACTURA",numero:number,secuencial:n,estado:"EMITIDA",pedidoId:order.id,pedidoNumero:txt(order.numero||order.id),clienteUid:txt(order.clienteUid),comprador:buyer(order),detalles:detail(order),totales:totals(order),pago:{metodo:txt(order.pago?.metodo),nombre:txt(order.pago?.nombre),estado:txt(order.pago?.estado||order.estadoPago)},entrega:order.entrega||{},fechaEmision:e.fecha?.value||today(),creadoEn:FV.serverTimestamp(),actualizadoEn:FV.serverTimestamp()};tx.set(ref,created);tx.set(lockRef,{tipoRegistro:"LOCK",sistema:"SIXTEEN_INTERNO",pedidoId:order.id,activeFacturaId:ref.id,actualizadoEn:FV.serverTimestamp()},{merge:true});tx.set(CFG,{tipoRegistro:"CONFIG",sistema:"SIXTEEN_INTERNO",proximoFactura:n+1,proximoNotaCredito:Math.max(1,Math.floor(num(cfg.proximoNotaCredito)||1)),proximoNotaDebito:Math.max(1,Math.floor(num(cfg.proximoNotaDebito)||1)),actualizadoEn:FV.serverTimestamp()},{merge:true});});if(created?.clienteUid){db.collection("notificaciones").doc(created.clienteUid).collection("items").add({tipo:"factura_emitida",titulo:"Factura SIXTEEN emitida",mensaje:`Tu factura ${created.numero} ya está disponible en Mi Cuenta.`,pedidoId:created.pedidoId,pedidoNumero:created.pedidoNumero,leida:false,creadoEn:FV.serverTimestamp()}).catch(()=>{});}setMsg(`Factura ${created.numero} generada correctamente.`);e.pedido.value="";renderPreview();setTimeout(()=>openPdf({...created,id:createdId}),100);}catch(err){console.error("Facturación SIXTEEN:",err);setMsg(err?.message||"No fue posible generar la factura.",true);}finally{e.generar.disabled=false;}}
function renderKpis(){const active=docs.filter(x=>x.estado!=="ANULADA");if(e.kTotal)e.kTotal.textContent=String(docs.length);if(e.kFac)e.kFac.textContent=String(active.filter(x=>x.tipoDocumento==="FACTURA").length);if(e.kNc)e.kNc.textContent=String(active.filter(x=>x.tipoDocumento==="NOTA_CREDITO").length);if(e.kMonto)e.kMonto.textContent=money(active.filter(x=>x.tipoDocumento==="FACTURA").reduce((s,x)=>s+num(x.totales?.importeTotal),0));const pending=docs.filter(x=>x.estado!=="EMITIDA").length;if(e.badge){e.badge.textContent=String(pending);e.badge.classList.toggle("vacio",pending===0);}}
function filtered(){const q=clean(e.buscar?.value),tp=txt(e.tipo?.value),st=txt(e.estado?.value);return docs.filter(x=>(!tp||x.tipoDocumento===tp)&&(!st||x.estado===st)&&(!q||clean([x.numero,x.pedidoNumero,x.referenciaNumero,x.comprador?.razonSocial,x.comprador?.identificacion,x.comprador?.email].join(" ")).includes(q)));}
function btn(label,action,id,cls="admin-table-btn"){const b=document.createElement("button");b.type="button";b.className=cls;b.textContent=label;b.dataset[action]=id;return b;}
function renderTable(){clear(e.body);const list=filtered().sort((a,b)=>(b.creadoEn?.seconds||0)-(a.creadoEn?.seconds||0));if(!list.length){const tr=document.createElement("tr"),td=document.createElement("td");td.colSpan=7;td.textContent="No hay documentos para mostrar.";tr.append(td);e.body.append(tr);return;}list.forEach(x=>{const tr=document.createElement("tr");const values=[[typeName(x.tipoDocumento),x.numero],[x.fechaEmision||"—"],[x.comprador?.razonSocial||"—",x.comprador?.identificacion||""],[x.pedidoNumero||x.referenciaNumero||"—"],[money(x.totales?.importeTotal)],[x.estado||"EMITIDA"]];values.forEach((arr,i)=>{const td=document.createElement("td");(Array.isArray(arr)?arr:[arr]).filter(Boolean).forEach((v,j)=>{const el=j===0?document.createElement("strong"):document.createElement("small");el.textContent=v;td.append(el)});tr.append(td)});const act=document.createElement("td");act.className="facturacion-actions";act.append(btn("PDF","invoicePdf",x.id),btn("EMAIL","invoiceEmail",x.id));if(x.estado!=="ANULADA")act.append(btn("ANULAR","invoiceCancel",x.id,"admin-table-btn danger"));tr.append(act);e.body.append(tr);});}
function refresh(){renderKpis();renderOrders();renderTable();fillNoteInvoices();}
function getDoc(id){return docs.find(x=>x.id===id)||null;}
function openPdf(item){if(!window.SIXTEEN_FACTURA_PDF){alert("No se cargó el generador PDF.");return;}if(!window.SIXTEEN_FACTURA_PDF.open(item))alert("Permite ventanas emergentes para abrir el documento.");}
async function sendEmail(item,button){const api=window.SIXTEEN_COMPROBANTE_EMAIL;if(!api){alert("No se cargó el módulo de correo.");return;}button.disabled=true;const old=button.textContent;button.textContent="ENVIANDO...";try{await api.send(item);await C.doc(item.id).set({correoEnviado:true,correoEnviadoEn:FV.serverTimestamp(),actualizadoEn:FV.serverTimestamp()},{merge:true});alert("Correo enviado.");}catch(err){console.error(err);alert(err?.message||"No fue posible enviar el correo.");}finally{button.disabled=false;button.textContent=old;}}
async function cancelDoc(item){if(!item||item.estado==="ANULADA")return;if(!confirm(`¿Anular ${item.numero}? El pedido y el inventario no serán modificados.`))return;try{await db.runTransaction(async tx=>{const ref=C.doc(item.id);const current=await tx.get(ref);if(!current.exists)throw new Error("El documento ya no existe.");tx.update(ref,{estado:"ANULADA",anuladoEn:FV.serverTimestamp(),actualizadoEn:FV.serverTimestamp()});if(item.tipoDocumento==="FACTURA"&&item.pedidoId){const lockRef=C.doc("lock_pedido_"+safeId(item.pedidoId));const lock=await tx.get(lockRef);if(lock.exists&&txt(lock.data()?.activeFacturaId)===item.id)tx.set(lockRef,{activeFacturaId:"",actualizadoEn:FV.serverTimestamp()},{merge:true});}});}catch(err){console.error(err);alert(err?.message||"No fue posible anular el documento.");}}
function fillNoteInvoices(){if(!e.noteInvoice)return;const val=e.noteInvoice.value;clear(e.noteInvoice);const o=document.createElement("option");o.value="";o.textContent="Selecciona una factura";e.noteInvoice.append(o);docs.filter(x=>x.tipoDocumento==="FACTURA"&&x.estado==="EMITIDA").forEach(x=>{const op=document.createElement("option");op.value=x.id;op.textContent=`${x.numero} · ${x.comprador?.razonSocial||"Cliente"} · ${money(x.totales?.importeTotal)}`;e.noteInvoice.append(op)});if([...e.noteInvoice.options].some(x=>x.value===val))e.noteInvoice.value=val;}
function openNote(type,trigger){noteType=type;lastFocus=trigger||document.activeElement;if(e.modalTitle)e.modalTitle.textContent=type==="NOTA_CREDITO"?"Nueva nota de crédito":"Nueva nota de débito";if(e.noteInfo)e.noteInfo.textContent=type==="NOTA_CREDITO"?"La nota de crédito disminuye comercialmente el valor de referencia y no modifica automáticamente el pedido ni el inventario.":"La nota de débito registra un valor adicional comercial y no modifica automáticamente el pedido ni el inventario.";if(e.noteForm)e.noteForm.reset();if(e.noteMsg)e.noteMsg.textContent="";fillNoteInvoices();e.modal.hidden=false;document.body.classList.add("modal-open");setTimeout(()=>e.noteInvoice?.focus(),0);}
function closeNote(){if(!e.modal||e.modal.hidden)return;e.modal.hidden=true;document.body.classList.remove("modal-open");lastFocus?.focus?.();}
async function createNote(ev){ev.preventDefault();const inv=getDoc(e.noteInvoice?.value);const value=Math.round(num(e.noteValue?.value)*100)/100;const reason=txt(e.noteReason?.value);if(!inv||inv.tipoDocumento!=="FACTURA"){e.noteMsg.textContent="Selecciona una factura válida.";return;}if(value<=0){e.noteMsg.textContent="Ingresa un valor mayor a cero.";return;}if(noteType==="NOTA_CREDITO"&&value>num(inv.totales?.importeTotal)){e.noteMsg.textContent="La nota de crédito no puede superar el total de la factura.";return;}if(reason.length<3){e.noteMsg.textContent="Escribe el motivo de la nota.";return;}e.noteSave.disabled=true;e.noteMsg.textContent="Generando nota...";try{let created=null;const ref=C.doc(`${noteType==="NOTA_CREDITO"?"nc":"nd"}_${safeId(inv.id)}_${Date.now()}`);await db.runTransaction(async tx=>{const cfgSnap=await tx.get(CFG);const cfg=cfgSnap.exists?cfgSnap.data():{};const key=noteType==="NOTA_CREDITO"?"proximoNotaCredito":"proximoNotaDebito";const n=Math.max(1,Math.floor(num(cfg[key])||1));const prefix=noteType==="NOTA_CREDITO"?"SIX-NC":"SIX-ND";created={tipoRegistro:"DOCUMENTO",sistema:"SIXTEEN_INTERNO",version:1,tipoDocumento:noteType,numero:seq(prefix,n),secuencial:n,estado:"EMITIDA",referenciaFacturaId:inv.id,referenciaNumero:inv.numero,pedidoId:inv.pedidoId||"",pedidoNumero:inv.pedidoNumero||"",clienteUid:inv.clienteUid||"",comprador:inv.comprador||{},pago:inv.pago||{},motivo:reason,totales:{subtotal:value,descuento:0,envio:0,importeTotal:value},fechaEmision:today(),creadoEn:FV.serverTimestamp(),actualizadoEn:FV.serverTimestamp()};tx.set(ref,created);tx.set(CFG,{tipoRegistro:"CONFIG",sistema:"SIXTEEN_INTERNO",[key]:n+1,actualizadoEn:FV.serverTimestamp()},{merge:true});});closeNote();setTimeout(()=>openPdf({...created,id:ref.id}),100);}catch(err){console.error(err);e.noteMsg.textContent=err?.message||"No fue posible generar la nota.";}finally{e.noteSave.disabled=false;}}
function csvCell(v){let s=txt(v).replace(/"/g,'""');if(/^[=+\-@]/.test(s))s="'"+s;return `"${s}"`;}
function exportCsv(){const list=filtered();if(!list.length){alert("No hay documentos para exportar.");return;}const lines=[["Tipo","Numero","Fecha","Cliente","Identificacion","Pedido/Referencia","Total","Estado"],...list.map(x=>[typeName(x.tipoDocumento),x.numero,x.fechaEmision,x.comprador?.razonSocial,x.comprador?.identificacion,x.pedidoNumero||x.referenciaNumero,num(x.totales?.importeTotal).toFixed(2),x.estado])].map(r=>r.map(csvCell).join(","));const blob=new Blob(["\ufeff"+lines.join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`SIXTEEN_facturacion_${today()}.csv`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
[e.buscar,e.tipo,e.estado].forEach(x=>x?.addEventListener(x===e.buscar?"input":"change",renderTable));e.pedido?.addEventListener("change",renderPreview);e.generar?.addEventListener("click",createInvoice);e.exportar?.addEventListener("click",exportCsv);e.openNc?.addEventListener("click",ev=>openNote("NOTA_CREDITO",ev.currentTarget));e.openNd?.addEventListener("click",ev=>openNote("NOTA_DEBITO",ev.currentTarget));e.closeModal?.addEventListener("click",closeNote);e.cancelModal?.addEventListener("click",closeNote);e.noteForm?.addEventListener("submit",createNote);e.modal?.addEventListener("click",ev=>{if(ev.target===e.modal)closeNote()});document.addEventListener("keydown",ev=>{if(ev.key==="Escape"&&!e.modal?.hidden)closeNote()});e.body.addEventListener("click",ev=>{const p=ev.target.closest("button[data-invoice-pdf]");if(p){openPdf(getDoc(p.dataset.invoicePdf));return;}const mail=ev.target.closest("button[data-invoice-email]");if(mail){sendEmail(getDoc(mail.dataset.invoiceEmail),mail);return;}const can=ev.target.closest("button[data-invoice-cancel]");if(can)cancelDoc(getDoc(can.dataset.invoiceCancel));});
if(e.fecha&&!e.fecha.value)e.fecha.value=today();
db.collection("pedidos").onSnapshot(s=>{orders=[];s.forEach(d=>orders.push({id:d.id,...d.data()}));renderOrders();},err=>{console.error("Pedidos facturación:",err);setMsg("No fue posible cargar pedidos.",true)});
C.onSnapshot(s=>{docs=[];s.forEach(d=>{const x={id:d.id,...d.data()};if(isInternal(x))docs.push(x)});refresh();},err=>{console.error("Facturación interna:",err);clear(e.body);const tr=document.createElement("tr"),td=document.createElement("td");td.colSpan=7;td.textContent="No fue posible cargar Facturación SIXTEEN.";tr.append(td);e.body.append(tr)});
});
